### ISSUE TITLE
dev........bat这个文件不支持谷歌64位的么？

### ISSUE THREAD

**Issue by xixiranran** [myfreeer/enableallExtensions#1]
大神帮忙解决下谢谢

**Comment by myfreeer** [comment]
[原作者](https://stackoverflow.com/users/3959875/woxxom)似乎已停止更新，根据[原帖](http://stackoverflow.com/a/30361260)[评论](https://stackoverflow.com/questions/30287907/how-to-get-rid-of-disable-developer-mode-extensions-pop-up/30361260#comment82512460_30361260)，Chrome 62及之后的版本失效，需要[手动修改](http://stackoverflow.com/a/30361260)

**Comment by xixiranran** [comment]
好的，我倒是看过这个网址，只是不知道失效了，谢谢你
